apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260526-155111-ukwncq1alpfn-service
spec:
  selector:
    app: enterprise-system-20260526-155111-ukwncq1alpfn
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
